AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'doc/**/*.xml'
    - '.pryrc'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'
    - '*.gemspec'

Metrics/LineLength:
  Max: 100
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false
